buildscript {
    repositories {
        maven { url = uri("http://127.0.0.1:8766") }
        maven { url = uri("https://dl.google.com/dl/android/maven2") }
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.2'
    }
}
