package defpackage;

import io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker;
import io.netty.handler.traffic.AbstractTrafficShapingHandler;

/* JADX INFO: compiled from: r8-map-id-605be6ced3201ebf27d05845df89146b03500986a7a8ae40fc58e667db41f02f */
/* JADX INFO: loaded from: classes.dex */
public final class df5 {
    public static final oa5 A;
    public static final oa5 B;
    public static final oa5 C;
    public static final oa5 D;
    public static final oa5 E;
    public static final oa5 F;
    public static final oa5 G;
    public static final oa5 H;
    public static final oa5 I;
    public static final oa5 J;
    public static final oa5 K;
    public static final oa5 L;
    public static final oa5 M;
    public static final oa5 N;
    public static final oa5 O;
    public static final oa5 P;
    public static final oa5 Q;
    public static final oa5 R;
    public static final oa5 S;
    public static final oa5 T;
    public static final oa5 U;
    public static final oa5 V;
    public static final oa5 W;
    public static final oa5 X;
    public static final oa5 Y;
    public static final oa5 Z;
    public static final oa5 a;
    public static final oa5 a0;
    public static final oa5 b;
    public static final oa5 b0;
    public static final oa5 c;
    public static final oa5 c0;
    public static final oa5 d;
    public static final oa5 d0;
    public static final oa5 e;
    public static final oa5 e0;
    public static final oa5 f;
    public static final oa5 f0;
    public static final oa5 g;
    public static final oa5 g0;
    public static final oa5 h;
    public static final oa5 h0;
    public static final oa5 i;
    public static final oa5 i0;
    public static final oa5 j;
    public static final oa5 j0;
    public static final oa5 k;
    public static final oa5 k0;
    public static final oa5 l;
    public static final oa5 l0;
    public static final oa5 m;
    public static final oa5 m0;
    public static final oa5 n;
    public static final oa5 n0;
    public static final oa5 o;
    public static final oa5 o0;
    public static final oa5 p;
    public static final oa5 p0;
    public static final oa5 q;
    public static final oa5 q0;
    public static final oa5 r;
    public static final oa5 r0;
    public static final oa5 s;
    public static final oa5 s0;
    public static final oa5 t;
    public static final oa5 t0;
    public static final oa5 u;
    public static final oa5 u0;
    public static final oa5 v;
    public static final oa5 v0;
    public static final oa5 w;
    public static final oa5 w0;
    public static final oa5 x;
    public static final oa5 y;
    public static final oa5 z;

    static {
        sn snVar = new sn(ma5.a(), true, true);
        a = snVar.t(10000L, "measurement.ad_id_cache_time");
        b = snVar.t(3600000L, "measurement.app_uninstalled_additional_ad_id_cache_time");
        c = snVar.v("measurement.config.bundle_for_all_apps_on_backgrounded", true);
        d = snVar.t(100L, "measurement.max_bundles_per_iteration");
        e = snVar.y("measurement.gbraid_campaign.campaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid");
        f = snVar.t(86400000L, "measurement.config.cache_time");
        snVar.y("measurement.log_tag", "FA");
        g = snVar.y("measurement.config.url_authority", "app-measurement.com");
        h = snVar.y("measurement.config.url_scheme", "https");
        i = snVar.t(1000L, "measurement.upload.debug_upload_interval");
        snVar.v("measurement.config.default_flag_values", true);
        j = snVar.t(3600000L, "measurement.session.engagement_interval");
        k = snVar.y("measurement.rb.attribution.event_params", "value|currency");
        l = snVar.y("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp");
        m = snVar.t(605000L, "measurement.upload.google_signal_max_queue_time");
        n = snVar.y("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d");
        snVar.t(0L, "measurement.id.upload.max_conversions_per_day");
        o = snVar.t(4L, "measurement.lifetimevalue.max_currency_tracked");
        p = snVar.t(1L, "measurement.dma_consent.max_daily_dcu_realtime_events");
        q = snVar.t(500L, "measurement.upload.max_event_parameter_value_length");
        r = snVar.t(100000L, "measurement.store.max_stored_events_per_app");
        s = snVar.t(50L, "measurement.experiment.max_ids");
        t = snVar.t(200L, "measurement.audience.filter_result_max_count");
        u = snVar.t(27L, "measurement.upload.max_item_scoped_custom_parameters");
        v = snVar.t(1000L, "measurement.rb.max_trigger_registrations_per_day");
        w = snVar.t(0L, "measurement.rb.attribution.max_trigger_uris_queried_at_once");
        x = snVar.t(7L, "measurement.rb.attribution.client.min_ad_services_version");
        y = snVar.t(60000L, "measurement.alarm_manager.minimum_interval");
        z = snVar.t(500L, "measurement.upload.minimum_delay");
        A = snVar.t(86400000L, "measurement.monitoring.sample_period_millis");
        B = snVar.t(3000L, "measurement.rb.attribution.notify_app_delay_millis");
        C = snVar.v("measurement.config.notify_trigger_uris_on_backgrounded", true);
        D = snVar.y("measurement.rb.attribution.app_allowlist", "");
        E = snVar.t(10000L, "measurement.upload.realtime_upload_interval");
        F = snVar.t(604800000L, "measurement.upload.refresh_blacklisted_config_interval");
        snVar.t(3600000L, "measurement.config.cache_time.service");
        G = snVar.t(5000L, "measurement.service_client.idle_disconnect_millis");
        snVar.y("measurement.log_tag.service", "FA-SVC");
        H = snVar.t(1000L, "measurement.service_client.reconnect_millis");
        snVar.y("measurement.sgtm.app_allowlist", WebSocketServerHandshaker.SUB_PROTOCOL_WILDCARD);
        I = snVar.t(240000L, "measurement.sgtm.batch.long_queuing_threshold");
        J = snVar.t(1800000L, "measurement.sgtm.batch.retry_interval");
        K = snVar.t(10L, "measurement.sgtm.batch.retry_max_count");
        L = snVar.t(21600000L, "measurement.sgtm.batch.retry_max_wait");
        M = snVar.y("measurement.sgtm.service_upload_apps_list", "");
        N = snVar.y("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504");
        O = snVar.t(5L, "measurement.sgtm.upload.batches_retrieval_limit");
        P = snVar.t(5000L, "measurement.sgtm.upload.max_queued_batches");
        Q = snVar.t(600000L, "measurement.sgtm.upload.min_delay_after_background");
        R = snVar.t(1000L, "measurement.sgtm.upload.min_delay_after_broadcast");
        S = snVar.t(5000L, "measurement.sgtm.upload.min_delay_after_startup");
        T = snVar.t(600000L, "measurement.sgtm.upload.retry_interval");
        U = snVar.t(21600000L, "measurement.sgtm.upload.retry_max_wait");
        V = snVar.t(86400000L, "measurement.upload.stale_data_deletion_interval");
        W = snVar.t(16L, "measurement.rb.attribution.max_retry_delay_seconds");
        X = snVar.t(90L, "measurement.rb.attribution.client.min_time_after_boot_seconds");
        Y = snVar.y("measurement.rb.attribution.uri_authority", "google-analytics.com");
        Z = snVar.t(864000000L, "measurement.rb.attribution.max_queue_time");
        a0 = snVar.y("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion");
        b0 = snVar.y("measurement.rb.attribution.query_parameters_to_remove", "");
        c0 = snVar.y("measurement.rb.attribution.uri_scheme", "https");
        d0 = snVar.t(604800000L, "measurement.sdk.attribution.cache.ttl");
        e0 = snVar.t(7200000L, "measurement.redaction.app_instance_id.ttl");
        f0 = snVar.t(43200000L, "measurement.upload.backoff_period");
        g0 = snVar.t(AbstractTrafficShapingHandler.DEFAULT_MAX_TIME, "measurement.upload.initial_upload_delay_time");
        h0 = snVar.t(3600000L, "measurement.upload.interval");
        i0 = snVar.t(65536L, "measurement.upload.max_bundle_size");
        j0 = snVar.t(100L, "measurement.upload.max_bundles");
        k0 = snVar.t(500L, "measurement.upload.max_conversions_per_day");
        l0 = snVar.t(1000L, "measurement.upload.max_error_events_per_day");
        m0 = snVar.t(1000L, "measurement.upload.max_events_per_bundle");
        n0 = snVar.t(100000L, "measurement.upload.max_events_per_day");
        o0 = snVar.t(50000L, "measurement.upload.max_public_events_per_day");
        p0 = snVar.t(518400000L, "measurement.upload.max_queue_time");
        q0 = snVar.t(10L, "measurement.upload.max_realtime_events_per_day");
        r0 = snVar.t(65536L, "measurement.upload.max_batch_size");
        s0 = snVar.t(6L, "measurement.upload.retry_count");
        t0 = snVar.t(1800000L, "measurement.upload.retry_time");
        u0 = snVar.y("measurement.upload.url", "https://app-measurement.com/a");
        v0 = snVar.t(3600000L, "measurement.upload.window_interval");
        w0 = snVar.y("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot");
    }
}
