apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.ippulse.scanner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ippulse.scanner'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

dependencies {
    implementation 'com.wireguard.android:tunnel:1.0.20230706'
    implementation 'dnsjava:dnsjava:3.5.2'
}
}
