plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ippulse.scanner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ippulse.scanner'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.github.heiher:hev-socks5-tunnel:2.17.1'
}
