package defpackage;

import io.netty.handler.traffic.AbstractTrafficShapingHandler;
import j$.util.DesugarCollections;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/* JADX INFO: compiled from: r8-map-id-605be6ced3201ebf27d05845df89146b03500986a7a8ae40fc58e667db41f02f */
/* JADX INFO: loaded from: classes.dex */
public abstract class r55 {
    public static final q55 A;
    public static final q55 A0;
    public static final q55 B;
    public static final q55 B0;
    public static final q55 C;
    public static final q55 C0;
    public static final q55 D;
    public static final q55 D0;
    public static final q55 E;
    public static final q55 E0;
    public static final q55 F;
    public static final q55 F0;
    public static final q55 G;
    public static final q55 G0;
    public static final q55 H;
    public static final q55 H0;
    public static final q55 I;
    public static final q55 I0;
    public static final q55 J;
    public static final q55 J0;
    public static final q55 K;
    public static final q55 K0;
    public static final q55 L;
    public static final q55 L0;
    public static final q55 M;
    public static final q55 M0;
    public static final q55 N;
    public static final q55 N0;
    public static final q55 O;
    public static final q55 O0;
    public static final q55 P;
    public static final q55 P0;
    public static final q55 Q;
    public static final q55 Q0;
    public static final q55 R;
    public static final q55 R0;
    public static final q55 S;
    public static final q55 S0;
    public static final q55 T;
    public static final q55 T0;
    public static final q55 U;
    public static final q55 U0;
    public static final q55 V;
    public static final q55 V0;
    public static final q55 W;
    public static final q55 W0;
    public static final q55 X;
    public static final q55 X0;
    public static final q55 Y;
    public static final q55 Y0;
    public static final q55 Z;
    public static final q55 Z0;
    public static final List a = DesugarCollections.synchronizedList(new ArrayList());
    public static final q55 a0;
    public static final q55 a1;
    public static final q55 b;
    public static final q55 b0;
    public static final q55 b1;
    public static final q55 c;
    public static final q55 c0;
    public static final q55 c1;
    public static final q55 d;
    public static final q55 d0;
    public static final q55 d1;
    public static final q55 e;
    public static final q55 e0;
    public static final q55 e1;
    public static final q55 f;
    public static final q55 f0;
    public static final q55 f1;
    public static final q55 g;
    public static final q55 g0;
    public static final q55 g1;
    public static final q55 h;
    public static final q55 h0;
    public static final q55 h1;
    public static final q55 i;
    public static final q55 i0;
    public static final q55 i1;
    public static final q55 j;
    public static final q55 j0;
    public static final q55 j1;
    public static final q55 k;
    public static final q55 k0;
    public static final q55 k1;
    public static final q55 l;
    public static final q55 l0;
    public static final q55 l1;
    public static final q55 m;
    public static final q55 m0;
    public static final q55 n;
    public static final q55 n0;
    public static final q55 o;
    public static final q55 o0;
    public static final q55 p;
    public static final q55 p0;
    public static final q55 q;
    public static final q55 q0;
    public static final q55 r;
    public static final q55 r0;
    public static final q55 s;
    public static final q55 s0;
    public static final q55 t;
    public static final q55 t0;
    public static final q55 u;
    public static final q55 u0;
    public static final q55 v;
    public static final q55 v0;
    public static final q55 w;
    public static final q55 w0;
    public static final q55 x;
    public static final q55 x0;
    public static final q55 y;
    public static final q55 y0;
    public static final q55 z;
    public static final q55 z0;

    static {
        DesugarCollections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, o84.L0, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, p84.A, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, o84.Y, false);
        e = a("measurement.config.cache_time", 86400000L, d84.Z, false);
        f = a("measurement.config.url_scheme", "https", c84.B0, false);
        g = a("measurement.config.url_authority", "app-measurement.com", l74.B0, false);
        h = a("measurement.upload.max_bundles", 100, q84.D0, false);
        i = a("measurement.upload.max_batch_size", 65536, p84.G0, false);
        j = a("measurement.upload.max_bundle_size", 65536, o84.H0, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, o84.J0, false);
        l = a("measurement.upload.max_events_per_day", 100000, d84.K0, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, q84.A, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, l74.A, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, c84.Y, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, d84.A, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, o84.X, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", p84.Y, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", q84.X, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", l74.X, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", c84.Z, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, d84.X, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, p84.Z, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, q84.Y, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, l74.Y, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, c84.y0, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, d84.Y, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, o84.Z, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, p84.y0, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, q84.Z, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, l74.Z, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, c84.z0, false);
        G = a("measurement.upload.backoff_period", 43200000L, o84.y0, false);
        H = a("measurement.upload.window_interval", 3600000L, p84.z0, false);
        I = a("measurement.upload.interval", 3600000L, q84.y0, false);
        J = a("measurement.upload.realtime_upload_interval", 10000L, l74.y0, false);
        K = a("measurement.upload.debug_upload_interval", 1000L, c84.A0, false);
        L = a("measurement.upload.minimum_delay", 500L, d84.y0, false);
        M = a("measurement.alarm_manager.minimum_interval", 60000L, o84.z0, false);
        N = a("measurement.upload.stale_data_deletion_interval", 86400000L, p84.A0, false);
        O = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, q84.z0, false);
        P = a("measurement.upload.initial_upload_delay_time", Long.valueOf(AbstractTrafficShapingHandler.DEFAULT_MAX_TIME), l74.z0, false);
        Q = a("measurement.upload.retry_time", 1800000L, d84.z0, false);
        R = a("measurement.upload.retry_count", 6, o84.A0, false);
        S = a("measurement.upload.max_queue_time", 518400000L, p84.B0, false);
        T = a("measurement.upload.google_signal_max_queue_time", 300000L, q84.A0, false);
        U = a("measurement.lifetimevalue.max_currency_tracked", 4, l74.A0, false);
        V = a("measurement.audience.filter_result_max_count", 200, c84.C0, false);
        W = a("measurement.upload.max_public_user_properties", 100, null, false);
        X = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        Y = a("measurement.upload.max_public_event_params", 100, null, false);
        Z = a("measurement.service_client.idle_disconnect_millis", 5000L, d84.A0, false);
        a0 = a("measurement.service_client.reconnect_millis", 1000L, o84.B0, false);
        Boolean bool = Boolean.FALSE;
        b0 = a("measurement.test.boolean_flag", bool, p84.C0, false);
        c0 = a("measurement.test.string_flag", "---", q84.B0, false);
        d0 = a("measurement.test.long_flag", -1L, c84.D0, false);
        a("measurement.test.cached_long_flag", -1L, d84.B0, true);
        e0 = a("measurement.test.int_flag", -2, o84.C0, false);
        f0 = a("measurement.test.double_flag", Double.valueOf(-3.0d), p84.D0, false);
        g0 = a("measurement.experiment.max_ids", 50, q84.C0, false);
        h0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, l74.C0, false);
        i0 = a("measurement.upload.max_event_parameter_value_length", 500, c84.E0, true);
        j0 = a("measurement.max_bundles_per_iteration", 100, d84.C0, false);
        k0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, o84.D0, false);
        l0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, p84.E0, false);
        m0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, l74.D0, false);
        n0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, c84.F0, false);
        o0 = a("measurement.rb.attribution.uri_scheme", "https", d84.D0, false);
        p0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", o84.E0, false);
        q0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", p84.F0, false);
        r0 = a("measurement.session.engagement_interval", 3600000L, q84.E0, false);
        s0 = a("measurement.rb.attribution.app_allowlist", "", l74.E0, false);
        t0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", c84.G0, false);
        u0 = a("measurement.rb.attribution.event_params", "value|currency", d84.E0, false);
        v0 = a("measurement.rb.attribution.query_parameters_to_remove", "", o84.F0, false);
        w0 = a("measurement.rb.attribution.max_queue_time", 864000000L, q84.F0, false);
        x0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, l74.F0, false);
        y0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, c84.H0, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, d84.F0, false);
        z0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, o84.G0, false);
        Boolean bool2 = Boolean.TRUE;
        A0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, p84.H0, false);
        B0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, q84.G0, false);
        C0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, l74.G0, false);
        D0 = a("measurement.quality.checksum", bool, null, false);
        E0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, c84.I0, false);
        F0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, d84.G0, false);
        G0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, p84.I0, true);
        H0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, q84.H0, false);
        I0 = a("measurement.integration.disable_firebase_instance_id", bool, l74.H0, false);
        J0 = a("measurement.collection.service.update_with_analytics_fix", bool, c84.J0, false);
        K0 = a("measurement.service.storage_consent_support_version", 203600, d84.H0, false);
        L0 = a("measurement.service.store_null_safelist", bool2, o84.I0, false);
        M0 = a("measurement.service.store_safelist", bool2, q84.I0, false);
        N0 = a("measurement.session_stitching_token_enabled", bool, l74.I0, false);
        O0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, c84.K0, true);
        P0 = a("measurement.gmscore_client_telemetry", bool, q84.L0, false);
        Q0 = a("measurement.rb.attribution.service", bool2, d84.I0, true);
        R0 = a("measurement.rb.attribution.client2", bool2, p84.J0, true);
        S0 = a("measurement.rb.attribution.uuid_generation", bool2, q84.J0, false);
        T0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, l74.J0, false);
        a("measurement.rb.attribution.followup1.service", bool, c84.L0, false);
        U0 = a("measurement.rb.attribution.retry_disposition", bool, d84.J0, false);
        V0 = a("measurement.client.sessions.enable_fix_background_engagement", bool, c84.N0, false);
        W0 = a("measurement.set_default_event_parameters_propagate_clear.service.dev", bool2, o84.K0, false);
        X0 = a("measurement.set_default_event_parameters_propagate_clear.client.dev", bool2, p84.K0, false);
        Y0 = a("measurement.service.ad_impression.convert_value_to_double", bool2, q84.K0, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, l74.K0, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, c84.M0, false);
        Z0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, q84.z, false);
        a1 = a("measurement.tcf.consent_fix", bool2, l74.z, false);
        b1 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, c84.X, false);
        c1 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, l74.f, false);
        d1 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, q84.f, false);
        e1 = a("measurement.service.fix_stop_bundling_bug", bool2, o84.z, false);
        f1 = a("measurement.fix_params_logcat_spam", bool2, d84.f, false);
        g1 = a("measurement.gbraid_campaign.stop_lgclid", bool, p84.L0, false);
        h1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", d84.z, false);
        i1 = a("measurement.edpb.service", bool, c84.A, false);
        j1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", o84.A, false);
        k1 = a("measurement.add_first_launch_logging_timestamp.service", bool, l74.L0, false);
        l1 = a("measurement.overlapping_bundles_fix", bool, p84.X, false);
    }

    public static q55 a(String str, Object obj, c35 c35Var, boolean z2) {
        q55 q55Var = new q55(str, obj, c35Var);
        if (z2) {
            a.add(q55Var);
        }
        return q55Var;
    }
}
