package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-605be6ced3201ebf27d05845df89146b03500986a7a8ae40fc58e667db41f02f */
/* JADX INFO: loaded from: classes.dex */
public final class vb0 {
    public int a;
    public final yb0 b;
    public final xb0 c;
    public final wb0 d;
    public final zb0 e;
    public HashMap f;

    public vb0() {
        yb0 yb0Var = new yb0();
        yb0Var.a = 0;
        yb0Var.b = 0;
        yb0Var.c = 1.0f;
        yb0Var.d = Float.NaN;
        this.b = yb0Var;
        xb0 xb0Var = new xb0();
        xb0Var.a = -1;
        xb0Var.b = 0;
        xb0Var.c = -1;
        xb0Var.d = Float.NaN;
        xb0Var.e = Float.NaN;
        xb0Var.f = Float.NaN;
        xb0Var.g = -1;
        xb0Var.h = null;
        xb0Var.i = -1;
        this.c = xb0Var;
        wb0 wb0Var = new wb0();
        wb0Var.a = false;
        wb0Var.d = -1;
        wb0Var.e = -1;
        wb0Var.f = -1.0f;
        wb0Var.g = true;
        wb0Var.h = -1;
        wb0Var.i = -1;
        wb0Var.j = -1;
        wb0Var.k = -1;
        wb0Var.l = -1;
        wb0Var.m = -1;
        wb0Var.n = -1;
        wb0Var.o = -1;
        wb0Var.p = -1;
        wb0Var.q = -1;
        wb0Var.r = -1;
        wb0Var.s = -1;
        wb0Var.t = -1;
        wb0Var.u = -1;
        wb0Var.v = -1;
        wb0Var.w = 0.5f;
        wb0Var.x = 0.5f;
        wb0Var.y = null;
        wb0Var.z = -1;
        wb0Var.A = 0;
        wb0Var.B = 0.0f;
        wb0Var.C = -1;
        wb0Var.D = -1;
        wb0Var.E = -1;
        wb0Var.F = 0;
        wb0Var.G = 0;
        wb0Var.H = 0;
        wb0Var.I = 0;
        wb0Var.J = 0;
        wb0Var.K = 0;
        wb0Var.L = 0;
        wb0Var.M = Integer.MIN_VALUE;
        wb0Var.N = Integer.MIN_VALUE;
        wb0Var.O = Integer.MIN_VALUE;
        wb0Var.P = Integer.MIN_VALUE;
        wb0Var.Q = Integer.MIN_VALUE;
        wb0Var.R = Integer.MIN_VALUE;
        wb0Var.S = Integer.MIN_VALUE;
        wb0Var.T = -1.0f;
        wb0Var.U = -1.0f;
        wb0Var.V = 0;
        wb0Var.W = 0;
        wb0Var.X = 0;
        wb0Var.Y = 0;
        wb0Var.Z = 0;
        wb0Var.a0 = 0;
        wb0Var.b0 = 0;
        wb0Var.c0 = 0;
        wb0Var.d0 = 1.0f;
        wb0Var.e0 = 1.0f;
        wb0Var.f0 = -1;
        wb0Var.g0 = 0;
        wb0Var.h0 = -1;
        wb0Var.l0 = false;
        wb0Var.m0 = false;
        wb0Var.n0 = true;
        wb0Var.o0 = 0;
        this.d = wb0Var;
        zb0 zb0Var = new zb0();
        zb0Var.a = 0.0f;
        zb0Var.b = 0.0f;
        zb0Var.c = 0.0f;
        zb0Var.d = 1.0f;
        zb0Var.e = 1.0f;
        zb0Var.f = Float.NaN;
        zb0Var.g = Float.NaN;
        zb0Var.h = -1;
        zb0Var.i = 0.0f;
        zb0Var.j = 0.0f;
        zb0Var.k = 0.0f;
        zb0Var.l = false;
        zb0Var.m = 0.0f;
        this.e = zb0Var;
        this.f = new HashMap();
    }

    public final void a(qb0 qb0Var) {
        wb0 wb0Var = this.d;
        qb0Var.e = wb0Var.h;
        qb0Var.f = wb0Var.i;
        qb0Var.g = wb0Var.j;
        qb0Var.h = wb0Var.k;
        qb0Var.i = wb0Var.l;
        qb0Var.j = wb0Var.m;
        qb0Var.k = wb0Var.n;
        qb0Var.l = wb0Var.o;
        qb0Var.m = wb0Var.p;
        qb0Var.n = wb0Var.q;
        qb0Var.o = wb0Var.r;
        qb0Var.s = wb0Var.s;
        qb0Var.t = wb0Var.t;
        qb0Var.u = wb0Var.u;
        qb0Var.v = wb0Var.v;
        ((ViewGroup.MarginLayoutParams) qb0Var).leftMargin = wb0Var.F;
        ((ViewGroup.MarginLayoutParams) qb0Var).rightMargin = wb0Var.G;
        ((ViewGroup.MarginLayoutParams) qb0Var).topMargin = wb0Var.H;
        ((ViewGroup.MarginLayoutParams) qb0Var).bottomMargin = wb0Var.I;
        qb0Var.A = wb0Var.R;
        qb0Var.B = wb0Var.Q;
        qb0Var.x = wb0Var.N;
        qb0Var.z = wb0Var.P;
        qb0Var.E = wb0Var.w;
        qb0Var.F = wb0Var.x;
        qb0Var.p = wb0Var.z;
        qb0Var.q = wb0Var.A;
        qb0Var.r = wb0Var.B;
        qb0Var.G = wb0Var.y;
        qb0Var.T = wb0Var.C;
        qb0Var.U = wb0Var.D;
        qb0Var.I = wb0Var.T;
        qb0Var.H = wb0Var.U;
        qb0Var.K = wb0Var.W;
        qb0Var.J = wb0Var.V;
        qb0Var.W = wb0Var.l0;
        qb0Var.X = wb0Var.m0;
        qb0Var.L = wb0Var.X;
        qb0Var.M = wb0Var.Y;
        qb0Var.P = wb0Var.Z;
        qb0Var.Q = wb0Var.a0;
        qb0Var.N = wb0Var.b0;
        qb0Var.O = wb0Var.c0;
        qb0Var.R = wb0Var.d0;
        qb0Var.S = wb0Var.e0;
        qb0Var.V = wb0Var.E;
        qb0Var.c = wb0Var.f;
        qb0Var.a = wb0Var.d;
        qb0Var.b = wb0Var.e;
        ((ViewGroup.MarginLayoutParams) qb0Var).width = wb0Var.b;
        ((ViewGroup.MarginLayoutParams) qb0Var).height = wb0Var.c;
        String str = wb0Var.k0;
        if (str != null) {
            qb0Var.Y = str;
        }
        qb0Var.Z = wb0Var.o0;
        qb0Var.setMarginStart(wb0Var.K);
        qb0Var.setMarginEnd(wb0Var.J);
        qb0Var.a();
    }

    public final Object clone() {
        vb0 vb0Var = new vb0();
        wb0 wb0Var = this.d;
        boolean z = wb0Var.a;
        wb0 wb0Var2 = vb0Var.d;
        wb0Var2.a = z;
        wb0Var2.b = wb0Var.b;
        wb0Var2.c = wb0Var.c;
        wb0Var2.d = wb0Var.d;
        wb0Var2.e = wb0Var.e;
        wb0Var2.f = wb0Var.f;
        wb0Var2.g = wb0Var.g;
        wb0Var2.h = wb0Var.h;
        wb0Var2.i = wb0Var.i;
        wb0Var2.j = wb0Var.j;
        wb0Var2.k = wb0Var.k;
        wb0Var2.l = wb0Var.l;
        wb0Var2.m = wb0Var.m;
        wb0Var2.n = wb0Var.n;
        wb0Var2.o = wb0Var.o;
        wb0Var2.p = wb0Var.p;
        wb0Var2.q = wb0Var.q;
        wb0Var2.r = wb0Var.r;
        wb0Var2.s = wb0Var.s;
        wb0Var2.t = wb0Var.t;
        wb0Var2.u = wb0Var.u;
        wb0Var2.v = wb0Var.v;
        wb0Var2.w = wb0Var.w;
        wb0Var2.x = wb0Var.x;
        wb0Var2.y = wb0Var.y;
        wb0Var2.z = wb0Var.z;
        wb0Var2.A = wb0Var.A;
        wb0Var2.B = wb0Var.B;
        wb0Var2.C = wb0Var.C;
        wb0Var2.D = wb0Var.D;
        wb0Var2.E = wb0Var.E;
        wb0Var2.F = wb0Var.F;
        wb0Var2.G = wb0Var.G;
        wb0Var2.H = wb0Var.H;
        wb0Var2.I = wb0Var.I;
        wb0Var2.J = wb0Var.J;
        wb0Var2.K = wb0Var.K;
        wb0Var2.L = wb0Var.L;
        wb0Var2.M = wb0Var.M;
        wb0Var2.N = wb0Var.N;
        wb0Var2.O = wb0Var.O;
        wb0Var2.P = wb0Var.P;
        wb0Var2.Q = wb0Var.Q;
        wb0Var2.R = wb0Var.R;
        wb0Var2.S = wb0Var.S;
        wb0Var2.T = wb0Var.T;
        wb0Var2.U = wb0Var.U;
        wb0Var2.V = wb0Var.V;
        wb0Var2.W = wb0Var.W;
        wb0Var2.X = wb0Var.X;
        wb0Var2.Y = wb0Var.Y;
        wb0Var2.Z = wb0Var.Z;
        wb0Var2.a0 = wb0Var.a0;
        wb0Var2.b0 = wb0Var.b0;
        wb0Var2.c0 = wb0Var.c0;
        wb0Var2.d0 = wb0Var.d0;
        wb0Var2.e0 = wb0Var.e0;
        wb0Var2.f0 = wb0Var.f0;
        wb0Var2.g0 = wb0Var.g0;
        wb0Var2.h0 = wb0Var.h0;
        wb0Var2.k0 = wb0Var.k0;
        int[] iArr = wb0Var.i0;
        if (iArr == null || wb0Var.j0 != null) {
            wb0Var2.i0 = null;
        } else {
            wb0Var2.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        wb0Var2.j0 = wb0Var.j0;
        wb0Var2.l0 = wb0Var.l0;
        wb0Var2.m0 = wb0Var.m0;
        wb0Var2.n0 = wb0Var.n0;
        wb0Var2.o0 = wb0Var.o0;
        xb0 xb0Var = this.c;
        int i = xb0Var.a;
        xb0 xb0Var2 = vb0Var.c;
        xb0Var2.a = i;
        xb0Var2.c = xb0Var.c;
        xb0Var2.e = xb0Var.e;
        xb0Var2.d = xb0Var.d;
        yb0 yb0Var = this.b;
        int i2 = yb0Var.a;
        yb0 yb0Var2 = vb0Var.b;
        yb0Var2.a = i2;
        yb0Var2.c = yb0Var.c;
        yb0Var2.d = yb0Var.d;
        yb0Var2.b = yb0Var.b;
        zb0 zb0Var = this.e;
        float f = zb0Var.a;
        zb0 zb0Var2 = vb0Var.e;
        zb0Var2.a = f;
        zb0Var2.b = zb0Var.b;
        zb0Var2.c = zb0Var.c;
        zb0Var2.d = zb0Var.d;
        zb0Var2.e = zb0Var.e;
        zb0Var2.f = zb0Var.f;
        zb0Var2.g = zb0Var.g;
        zb0Var2.h = zb0Var.h;
        zb0Var2.i = zb0Var.i;
        zb0Var2.j = zb0Var.j;
        zb0Var2.k = zb0Var.k;
        zb0Var2.l = zb0Var.l;
        zb0Var2.m = zb0Var.m;
        vb0Var.a = this.a;
        return vb0Var;
    }
}
