syntax = "proto3";

option java_package = "com.getsurfboard.vpn.proto";

message DnsQueryInfo {
    int32 session_id = 1;
    bytes dns_query = 2;
    int32 uid = 3;
    string source_ip = 4;
    int32 source_port = 5;
    string dest_ip = 6;
    int32 dest_port = 7;
}

message DnsQueryStrategy {
    int32 type = 1;
    bytes dns_response = 2;
    bytes dns_query = 3;
    string server = 4;
    int32 port = 5;
    int32 uid = 6;
}

message TrafficInfo {
    int32 session_id = 1;
    int32 proto = 2;
    int32 uid = 3;
    string host = 4;
    string source_ip = 5;
    int32 source_port = 6;
    string dest_ip = 7;
    int32 dest_port = 8;
    int32 length = 9;
    string proxy_name = 10;
    string protocol = 11;
    string path = 12;
    string user_agent = 13;
}

message ProxyStrategy {
    int32 type = 1;
    int32 uid = 2;
    string host = 3;
    string proxy_name = 4;
    int32 port = 5;
}
